---
- name: Install sysconfig for internal I/F
  template: src="ifcfg-int" dest="/etc/sysconfig/network-scripts/ifcfg-{{intif}}" mode=0644

- name: Install sysconfig for external I/F
  template: src="ifcfg-ext" dest="/etc/sysconfig/network-scripts/ifcfg-{{extif}}" mode=0644

#######################################################################
#
- name: Create setup directory
  file: path="{{ setup_dir }}" owner=root group=root mode=0755 state=directory

- name: Install setup files
  copy: src="{{ item }}" dest="{{ setup_dir }}/" owner=root mode=0755
  with_items:
    - setup-network.sh

- name: Install config files
  template: src="config-network" dest="{{ setup_dir }}/" owner=root

- name: Install password file
  template: src=pass.txt dest="{{ setup_dir }}/" owner=root group=root mode=0600

- name: Setup network
  command: "{{ setup_dir }}/setup-network.sh {{ setup_dir }}/config-network"
  register: setup_result
  ignore_errors: True
  changed_when: setup_result.rc == 2

- name: Check setup script error
  fail: msg="setup failed"
  when: setup_result.rc != 0 and setup_result.rc != 2
