---
- name: Create setup directory for controller
  file: path="{{setup_dir}}" owner=root group=root mode=0755 state=directory

- name: Install setup files for controller
  copy: src="{{item}}" dest="{{setup_dir}}/" owner=root mode=0755
  with_items:
    - setup-controller.sh
    - service-def-keystone.sh
    - service-def-nova.sh
    - service-def-glance.sh
    - service-def-cinder-v1.sh
    - service-def-cinder-v2.sh
    - service-def-ceilometer.sh
    - service-def-neutron.sh

- name: Install config files for controller
  template: src=config-controller dest="{{setup_dir}}/" owner=root group=root mode=0600

- name: Install password files
  template: src="{{item}}" dest="{{setup_dir}}/" owner=root group=root mode=0600
  with_items:
    - pass.txt
    - openrc.sh
    - demorc.sh

- name: Setup controller
  command: "{{setup_dir}}/setup-controller.sh {{setup_dir}}/config-controller"
  register: setup_result
  ignore_errors: True
  changed_when: setup_result.rc == 2

- name: Check script error for controller
  fail: msg="setup failed"
  when: setup_result.rc != 0 and setup_result.rc != 2
