SERVICE_NAME=nova
SERVICE_PASS=${NOVA_PASS}
SERVICE_EMAIL=nova@localhost
SERVICE_TYPE=compute
SERVICE_DESCRIPTION="OpenStack Compute"
SERVICE_URL_PUBLIC="http://${CONTROLLER_HOSTNAME}:8774/v2/%(tenant_id)s"
SERVICE_URL_INTERNAL="http://${CONTROLLER_HOSTNAME}:8774/v2/%(tenant_id)s"
SERVICE_URL_ADMIN="http://${CONTROLLER_HOSTNAME}:8774/v2/%(tenant_id)s"

