SERVICE_NAME=keystone
SERVICE_PASS=
SERVICE_EMAIL=
SERVICE_TYPE=identity
SERVICE_DESCRIPTION="OpenStack Identity"
SERVICE_URL_PUBLIC=http://${CONTROLLER_HOSTNAME}:5000/v2.0
SERVICE_URL_INTERNAL=http://${CONTROLLER_HOSTNAME}:5000/v2.0
SERVICE_URL_ADMIN=http://${CONTROLLER_HOSTNAME}:35357/v2.0

export OS_SERVICE_TOKEN=${ADMIN_TOKEN}
export OS_SERVICE_ENDPOINT=${SERVICE_URL_ADMIN}
