SERVICE_NAME=ironic
SERVICE_PASS=${IRONIC_PASS}
SERVICE_EMAIL=ironic@localhost
SERVICE_TYPE=baremetal
SERVICE_DESCRIPTION="Ironic bare metal provisioning service"
SERVICE_URL_PUBLIC="http://${CONTROLLER_HOSTNAME}:6385"
SERVICE_URL_INTERNAL="http://${CONTROLLER_HOSTNAME}:6385"
SERVICE_URL_ADMIN="http://${CONTROLLER_HOSTNAME}:6385"

