SERVICE_NAME=neutron
SERVICE_PASS=${NEUTRON_PASS}
SERVICE_EMAIL=neutron@localhost
SERVICE_TYPE=network
SERVICE_DESCRIPTION="Openstack Networking"
SERVICE_URL_PUBLIC="http://${CONTROLLER_HOSTNAME}:9696"
SERVICE_URL_INTERNAL="http://${CONTROLLER_HOSTNAME}:9696"
SERVICE_URL_ADMIN="http://${CONTROLLER_HOSTNAME}:9696"

