SERVICE_NAME=heat
SERVICE_PASS=${HEAT_PASS}
SERVICE_EMAIL=heat@localhost
SERVICE_TYPE=orchestration
SERVICE_DESCRIPTION="Orchestration"
SERVICE_URL_PUBLIC="http://${CONTROLLER_HOSTNAME}:8004/v1/%(tenant_id)s"
SERVICE_URL_INTERNAL="http://${CONTROLLER_HOSTNAME}:8004/v1/%(tenant_id)s"
SERVICE_URL_ADMIN="http://${CONTROLLER_HOSTNAME}:8004/v1/%(tenant_id)s"

