SERVICE_NAME=cinder
SERVICE_PASS=${CINDER_PASS}
SERVICE_EMAIL=cinder@localhost
SERVICE_TYPE=volume
SERVICE_DESCRIPTION="Cinder Volume Service"
SERVICE_URL_PUBLIC="http://${CONTROLLER_HOSTNAME}:8776/v1/%(tenant_id)s"
SERVICE_URL_INTERNAL="http://${CONTROLLER_HOSTNAME}:8776/v1/%(tenant_id)s"
SERVICE_URL_ADMIN="http://${CONTROLLER_HOSTNAME}:8776/v1/%(tenant_id)s"

