SERVICE_NAME=cinderv2
SERVICE_PASS=${CINDER_PASS}
SERVICE_EMAIL=
SERVICE_TYPE=volumev2
SERVICE_DESCRIPTION="OpenStack Block Storage"
SERVICE_URL_PUBLIC="http://${CONTROLLER_HOSTNAME}:8776/v2/%(tenant_id)s"
SERVICE_URL_INTERNAL="http://${CONTROLLER_HOSTNAME}:8776/v2/%(tenant_id)s"
SERVICE_URL_ADMIN="http://${CONTROLLER_HOSTNAME}:8776/v2/%(tenant_id)s"

