SERVICE_NAME=glance
SERVICE_PASS=${GLANCE_PASS}
SERVICE_EMAIL=glance@localhost
SERVICE_TYPE=image
SERVICE_DESCRIPTION="Glance Image Service"
SERVICE_URL_PUBLIC=http://${CONTROLLER_HOSTNAME}:9292
SERVICE_URL_INTERNAL=http://${CONTROLLER_HOSTNAME}:9292
SERVICE_URL_ADMIN=http://${CONTROLLER_HOSTNAME}:9292

