SERVICE_NAME=heat-cfn
SERVICE_PASS=${HEAT_PASS}
SERVICE_EMAIL=
SERVICE_TYPE=cloudformation
SERVICE_DESCRIPTION="Orchestration"
SERVICE_URL_PUBLIC="http://${CONTROLLER_HOSTNAME}:8000/v1"
SERVICE_URL_INTERNAL="http://${CONTROLLER_HOSTNAME}:8000/v1"
SERVICE_URL_ADMIN="http://${CONTROLLER_HOSTNAME}:8000/v1"

